node {
        checkout scm
        withDockerContainer(args: '-p 3000:3000', image: 'python:2-alpine') {
                stage('Build') {
                        sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                }
                stage('Test') {
                        withDockerContainer(args: '-p 3000:3000', image: 'qnib/pytest') {
				sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
			}
                }
        }
}
